//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Control.Asistencia.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaLaboral
    {
        public int IdDiaLaboral { get; set; }
        public Nullable<int> Empleado { get; set; }
        public Nullable<int> HoraEntrada { get; set; }
        public Nullable<int> HoraSalida { get; set; }
        public Nullable<System.DateTime> FechaDia { get; set; }
        public string Asistencia { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
        public virtual EntradaLaboral EntradaLaboral { get; set; }
        public virtual SalidaLaboral SalidaLaboral { get; set; }
    }
}
