//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Control.Asistencia.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class horariodetalle
    {
        public int hordet_id { get; set; }
        public Nullable<int> hordet_idhorario { get; set; }
        public string hordet_hora { get; set; }
        public Nullable<int> hordet_idestado { get; set; }
        public string hordet_descripcion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
