//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Control.Asistencia.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.ModulosUsuario = new HashSet<ModulosUsuario>();
        }
    
        public string Usu_Nombre { get; set; }
        public string Usu_Contraseña { get; set; }
        public string Usu_NombreCompleto { get; set; }
        public Nullable<System.DateTime> Usu_FechaCaduca { get; set; }
        public string Usu_Estado { get; set; }
        public string Usu_Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulosUsuario> ModulosUsuario { get; set; }
    }
}
